rvv: add configuration and command-line option
1. configure option "--with-varch"
the option defines the default u-arch implementatiton-decided parameter

  VLEN:  vector register length in bit
  SLEN:  striping distance in bit
  ELEN:  max element size in bit

  ex: --with-vector=v128:e32:s128

2. add __int128_t type checking

3. add --varch command option and help message

  ex: --varch=v512:e64:s512

Signed-off-by: Dave Wen <dave.wen@sifive.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -701,6 +701,7 @@ enable_option_checking
 enable_stow
 enable_optional_subprojects
 with_isa
+with_varch
 enable_commitlog
 enable_histogram
 enable_dirty
@@ -1358,6 +1359,8 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-isa=RV64IMAFDC   Sets the default RISC-V ISA
+  --with-varch=v128:e32:s128
+                          Sets the default vector config
 
 Some influential environment variables:
   CC          C compiler command
@@ -1638,6 +1641,60 @@ $as_echo "$ac_res" >&6; }
   eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
 
 } # ac_fn_cxx_check_header_compile
+
+# ac_fn_cxx_check_type LINENO TYPE VAR INCLUDES
+# ---------------------------------------------
+# Tests whether TYPE exists after having included INCLUDES, setting cache
+# variable VAR accordingly.
+ac_fn_cxx_check_type ()
+{
+  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
+  { $as_echo "$as_me:${as_lineno-$LINENO}: checking for $2" >&5
+$as_echo_n "checking for $2... " >&6; }
+if eval \${$3+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  eval "$3=no"
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+$4
+int
+main ()
+{
+if (sizeof ($2))
+	 return 0;
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+$4
+int
+main ()
+{
+if (sizeof (($2)))
+	    return 0;
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+
+else
+  eval "$3=yes"
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+eval ac_res=\$$3
+	       { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_res" >&5
+$as_echo "$ac_res" >&6; }
+  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
+
+} # ac_fn_cxx_check_type
 
 # ac_fn_cxx_try_link LINENO
 # -------------------------
@@ -4288,6 +4345,18 @@ fi
 
 
 #-------------------------------------------------------------------------
+# Checks for type
+#-------------------------------------------------------------------------
+
+ac_fn_cxx_check_type "$LINENO" "__int128_t" "ac_cv_type___int128_t" "$ac_includes_default"
+if test "x$ac_cv_type___int128_t" = xyes; then :
+
+else
+  echo "error: spike requires 128 integer suuport"; exit 1
+fi
+
+
+#-------------------------------------------------------------------------
 # Default compiler flags
 #-------------------------------------------------------------------------
 
@@ -4471,6 +4540,24 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 fi
+
+
+
+# Check whether --with-varch was given.
+if test "${with_varch+set}" = set; then :
+  withval=$with_varch;
+cat >>confdefs.h <<_ACEOF
+#define DEFAULT_VARCH "$withval"
+_ACEOF
+
+else
+
+cat >>confdefs.h <<_ACEOF
+#define DEFAULT_VARCH "v128:e32:s128"
+_ACEOF
+
+fi
+
 
 
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for library containing dlopen" >&5
